project:
  type: website
  title: "GeoPov - "

website:
  navbar:
    title: "Data & Methods"
    logo-href: index.qmd
    background: white
    foreground: "#0071bc"
    search: true
    left:
      - text: "Data"
        menu:
          - text: "Data"
            href: index.qmd#data
          - text: "By theme"
          - text: "People"
            href: data/people.qmd
          - text: "Planet"
            href: data/planet.qmd
          - text: "Prosperity"
            href: data/prosperity.qmd
          - text: "Infrastructure"
            href: data/infrastructure.qmd
          - text: "Digital"
            href: data/digital.qmd
          - text: "Boundaries"
            href: data/boundaries.qmd
          - text: "Curated datasets"
          - text: "Geocoded GMD data"
            href: index.qmd#geocoded-gmd-data
          - text: "Space2Stats"
            href: index.qmd#space2stats-data

      - text: "Methods"
        menu:
          - text: "Methods"
            href: index.qmd#methods-and-code
          - text: "By type"
          - text: "Aggregate"
            href: methods/aggregate.qmd
          - text: "Merge"
            href: methods/merge.qmd
          - text: "Map"
            href: methods/map.qmd
          - text: "Analyze"
            href: methods/analyze.qmd

      - text: "Applications"
        href: index.qmd#applications
      - text: "Contribute"
        href: index.qmd#contribute
      - text: "Contact us"
        href: "mailto:bbrunckhorst@worldbank.org?subject=GeoPov%20data%20and%20methods%20repository"

  page-footer:
    background: "#000000"
    foreground: "#808080"
    right: "Â© 2025 The World Bank Group, All Rights Reserved."
    left:
      - text: IBRD
        href: http://www.worldbank.org/en/who-we-are/ibrd
      - text: IDA
        href: http://www.worldbank.org/ida
      - text: IFC
        href: http://www.ifc.org/
      - text: MIGA
        href: http://www.miga.org/
      - text: ICSID
        href: http://icsid.worldbank.org/

editor: visual
code-fold: true
format:
  html:
    page-layout: custom
    title-block-banner: "#f6f6f6"
    title-block-banner-color: "#333333"
    theme: style.css
#    template-partials:
#      - title-block.html

resources:
  - fonts/*
  - style.css

